version: '3'

services:
  nacos:
    image: nacos/nacos-server:1.4.2
    ports:
      - "8848:8848"
    restart: always
    environment:
      MODE: standalone

  zookeeper:
    image: 'bitnami/zookeeper:3.6'
    ports:
      - '2181:2181'
    volumes:
      - ./zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
      - '9092:9092'
    volumes:
      - ./kafka:/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: "bitnami/redis:6.2.10"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/bitnami/redis/data
    restart: always
    environment:
      - REDIS_PASSWORD=yqhp@123..Aa88

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: yqhp@123..Aa88
      MYSQL_ROOT_HOST: '%'

  minio:
    image: "bitnami/minio:2023.3.24"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=yqhp@123..Aa88