version: '3'

services:
  nacos: # https://github.com/nacos-group/nacos-docker/blob/master/example/standalone-derby.yaml
    image: nacos/nacos-server:v2.2.0
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone

  zookeeper:
    image: 'bitnami/zookeeper:3.6'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: "bitnami/redis:6.2.10"
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=yqhp@123..Aa88

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: yqhp@123..Aa88
      MYSQL_ROOT_HOST: '%'

  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=yqhp@123..Aa88
    command:
      server /data