server:
  port: 8866
  servlet:
    context-path: /oss
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use
    threads:
      max: 1000 # Maximum amount of worker threads.
      min-spare: 10 # Minimum amount of worker threads.

spring:
  application:
    name: file-service

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

oss:
  minio:
    url: ${MINIO_URL:http://127.0.0.1:9000}
    bucket: yqhp
    accessKey: ${MINIO_ACCESS_KEY:admin}
    secretKey: ${MINIO_SECRET_KEY:yqhp@123..Aa88}