name: Console To DockerHub

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn install
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./console/console-web
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/jiangyitao/yqhp-console:latest
            registry.cn-hangzhou.aliyuncs.com/jiangyitao/yqhp-console:0.3.0